http_path = "/"
css_dir = "css"
sass_dir = "scss"
images_dir = "images"
fonts_dir = "fonts"
output_style = :nested
relative_assets = true
line_comments = false
sass_options = {:debug_info=>false}
sourcemap = false
